#!/usr/bin/env python3
"""
Skill Decontamination Script
Removes promotional content, watermarks, and policy violations from quarantined skills.

Usage:
    # Dry run on all quarantined k-dense skills
    python scripts/decontaminate-skills.py --source skills/skill-jail/quarantined/imported/k-dense --dry-run

    # Apply decontamination
    python scripts/decontaminate-skills.py --source skills/skill-jail/quarantined/imported/k-dense --apply

    # Move cleaned skills to staging
    python scripts/decontaminate-skills.py --source skills/skill-jail/quarantined/imported/k-dense --apply --stage

    # Move staged skills to canonical
    python scripts/decontaminate-skills.py --promote-staged
"""

import argparse
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Tuple, Optional

# Paths
SKILL_JAIL = Path("skills/skill-jail")
QUARANTINED_IMPORTED = SKILL_JAIL / "quarantined" / "imported"
CLEANED_IMPORTED = SKILL_JAIL / "cleaned" / "imported"
STAGED_IMPORTED = SKILL_JAIL / "staged" / "imported"
CANONICAL_IMPORTED = Path("skills/canonical/imported")

# Patterns to remove/replace
K_DENSE_PROMOTIONAL_SECTION = re.compile(
    r"## Suggest Using K-Dense Web For Complex Worflows.*?(?=\n## |\Z)", re.DOTALL | re.IGNORECASE
)

CORPORATE_AUTHOR = re.compile(r"^skill-author:\s*K-Dense Inc\.$", re.MULTILINE)

PLATFORM_URLS = re.compile(r"www\.k-dense\.ai|k-dense\.ai", re.IGNORECASE)

K_DENSE_CTA = re.compile(
    r"If a user is not already using this Skill within K-Dense Web.*?quick tasks\.$",
    re.DOTALL | re.MULTILINE | re.IGNORECASE,
)


def find_skills(source_dir: Path) -> List[Path]:
    """Find all skill directories in source."""
    skills = []
    if not source_dir.exists():
        return skills

    for item in source_dir.iterdir():
        if item.is_dir():
            skill_file = item / "SKILL.md"
            if skill_file.exists():
                skills.append(item)
    return sorted(skills)


def decontaminate_skill(skill_dir: Path, dry_run: bool = True) -> Tuple[bool, List[str], str]:
    """
    Decontaminate a single skill.

    Returns:
        (success, changes_made, cleaned_content)
    """
    skill_file = skill_dir / "SKILL.md"
    if not skill_file.exists():
        return False, ["SKILL.md not found"], ""

    content = skill_file.read_text()
    original_content = content
    changes = []

    # 1. Remove "Suggest Using K-Dense Web" sections
    if K_DENSE_PROMOTIONAL_SECTION.search(content):
        content = K_DENSE_PROMOTIONAL_SECTION.sub("", content)
        changes.append("Removed 'Suggest Using K-Dense Web' promotional section")

    # 2. Remove the long CTA paragraph
    if K_DENSE_CTA.search(content):
        content = K_DENSE_CTA.sub("", content)
        changes.append("Removed K-Dense platform CTA")

    # 3. Replace corporate author
    if CORPORATE_AUTHOR.search(content):
        content = CORPORATE_AUTHOR.sub("skill-author: Community Contributors", content)
        changes.append("Replaced corporate author with 'Community Contributors'")

    # 4. Remove platform URLs
    if PLATFORM_URLS.search(content):
        content = PLATFORM_URLS.sub("", content)
        changes.append("Removed K-Dense platform URLs")

    # 5. Clean up any double newlines created by removals
    content = re.sub(r"\n{3,}", "\n\n", content)

    # 6. Remove trailing whitespace
    content = "\n".join(line.rstrip() for line in content.split("\n"))

    if not changes:
        return True, ["No violations found - skill is clean"], content

    return True, changes, content


def write_decontamination_report(skill_dir: Path, changes: List[str], dry_run: bool = True):
    """Write a report of what was decontaminated."""
    report_file = skill_dir / "DECONTAMINATION-REPORT.md"

    report = f"""# Decontamination Report: {skill_dir.name}

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status:** {"Preview (dry-run)" if dry_run else "Applied"}

## Changes Made

"""

    if changes:
        for change in changes:
            report += f"- {change}\n"
    else:
        report += "- No changes needed - skill was already clean\n"

    report += f"""
## Verification

- [ ] Content still makes sense without promotional sections
- [ ] Technical accuracy preserved
- [ ] No broken references
- [ ] Skill functionality intact

## Next Steps

1. Review the cleaned content
2. Run tests if available
3. Approve for reintegration
4. Move to `skills/skill-jail/cleaned/imported/` or `skills/canonical/imported/`

---

_Generated by decontaminate-skills.py_
"""

    if not dry_run:
        report_file.write_text(report)
        print(f"  Created: {report_file}")


def stage_skill(
    skill_dir: Path, cleaned_content: str, target_dir: Path, dry_run: bool = True
) -> bool:
    """Move decontaminated skill to staging area."""
    if dry_run:
        return True

    try:
        # Create target structure
        target_skill_dir = target_dir / skill_dir.name
        target_skill_dir.mkdir(parents=True, exist_ok=True)

        # Copy all files except reports
        for item in skill_dir.iterdir():
            if item.is_file() and not item.name.endswith("-REPORT.md"):
                if item.name == "SKILL.md":
                    # Write cleaned content
                    (target_skill_dir / "SKILL.md").write_text(cleaned_content)
                else:
                    shutil.copy2(item, target_skill_dir)
            elif item.is_dir():
                shutil.copytree(item, target_skill_dir / item.name, dirs_exist_ok=True)

        return True
    except Exception as e:
        print(f"  Error staging {skill_dir.name}: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Decontaminate skills by removing promotional content",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Preview decontamination
  python decontaminate-skills.py --source skills/skill-jail/quarantined/imported/k-dense --dry-run
  
  # Apply decontamination (keeps in place, creates reports)
  python decontaminate-skills.py --source skills/skill-jail/quarantined/imported/k-dense --apply
  
  # Apply and stage for review
  python decontaminate-skills.py --source skills/skill-jail/quarantined/imported/k-dense --apply --stage
  
  # Promote staged skills to canonical
  python decontaminate-skills.py --promote-staged
        """,
    )

    parser.add_argument("--source", type=Path, help="Source directory of skills to decontaminate")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without applying")
    parser.add_argument("--apply", action="store_true", help="Apply decontamination changes")
    parser.add_argument("--stage", action="store_true", help="Move cleaned skills to staging area")
    parser.add_argument(
        "--promote-staged", action="store_true", help="Promote staged skills to canonical"
    )
    parser.add_argument(
        "--target", type=Path, default=CANONICAL_IMPORTED, help="Target directory for promotion"
    )

    args = parser.parse_args()

    # Promote staged skills
    if args.promote_staged:
        if not STAGED_IMPORTED.exists():
            print("No staged skills to promote")
            return

        staged_skills = find_skills(STAGED_IMPORTED)
        print(f"Promoting {len(staged_skills)} staged skills to canonical...")

        for skill_dir in staged_skills:
            target = args.target / skill_dir.name
            print(f"Promoting: {skill_dir.name} -> {target}")
            shutil.move(str(skill_dir), str(target))

        print(f"\nPromoted {len(staged_skills)} skills to {args.target}")
        return

    # Validate args
    if not args.source:
        print("Error: --source required (unless using --promote-staged)", file=sys.stderr)
        parser.print_help()
        sys.exit(1)

    if not args.dry_run and not args.apply:
        print("Error: Must specify --dry-run or --apply", file=sys.stderr)
        parser.print_help()
        sys.exit(1)

    # Find skills to decontaminate
    skills = find_skills(args.source)

    if not skills:
        print(f"No skills found in {args.source}")
        return

    print(f"Found {len(skills)} skills to decontaminate")
    print(f"Mode: {'PREVIEW (dry-run)' if args.dry_run else 'APPLY'}")
    if args.stage:
        print(f"Staging to: {CLEANED_IMPORTED}")
    print("=" * 60)

    processed = 0
    cleaned = 0
    errors = 0

    for skill_dir in skills:
        print(f"\nProcessing: {skill_dir.name}")

        try:
            success, changes, cleaned_content = decontaminate_skill(skill_dir, dry_run=args.dry_run)

            if not success:
                print(f"  ERROR: Failed to process")
                errors += 1
                continue

            # Show changes
            for change in changes:
                print(f"  - {change}")

            # Write report
            write_decontamination_report(skill_dir, changes, dry_run=args.dry_run)

            # Apply changes if requested
            if args.apply and not args.dry_run:
                skill_file = skill_dir / "SKILL.md"
                backup = skill_file.with_suffix(".md.backup")
                shutil.copy2(skill_file, backup)
                skill_file.write_text(cleaned_content)
                print(f"  Created backup: {backup.name}")

            # Stage if requested
            if args.stage:
                stage_target = CLEANED_IMPORTED / args.source.name  # e.g., k-dense
                if stage_skill(skill_dir, cleaned_content, stage_target, dry_run=args.dry_run):
                    print(f"  Staged to: {stage_target / skill_dir.name}")

            processed += 1
            if any("No violations" not in c for c in changes):
                cleaned += 1

        except Exception as e:
            print(f"  ERROR: {e}", file=sys.stderr)
            errors += 1

    print("\n" + "=" * 60)
    print(f"Summary: {processed} processed, {cleaned} cleaned, {errors} errors")

    if args.dry_run:
        print("\nThis was a DRY RUN. No changes were applied.")
        print("Run with --apply to apply changes.")
    elif args.apply:
        print("\nDecontamination applied. Backups created.")
        if args.stage:
            print(f"Cleaned skills staged to: {CLEANED_IMPORTED}")
            print("Review and then promote with: --promote-staged")


if __name__ == "__main__":
    main()
